name: PR Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-pr:
    name: Validate PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v5

      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
